In [61]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv('uber.csv')
df.head()

,sr,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,52:06.0,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,04:56.0,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,45:00.0,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,22:21.0,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,47:00.0,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [63]:
df.shape

(200000, 9)

In [64]:
df.isnull().sum()

sr                   0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [65]:
# Drop the row who contain null value
df.dropna(inplace=True)
df.head()

,sr,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,52:06.0,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,04:56.0,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,45:00.0,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,22:21.0,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,47:00.0,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [66]:
df.shape

(199999, 9)

In [67]:
df.describe()

,sr,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,1.999990e+05,199999.000000,199999.000000,199999.000000,199999.000000,199999.000000,199999.000000
mean,2.771248e+07,11.359892,-72.527631,39.935881,-72.525292,39.923890,1.684543
std,1.601386e+07,9.901760,11.437815,7.720558,13.117408,6.794829,1.385995
min,1.000000e+00,-52.000000,-1340.648410,-74.015515,-3356.666300,-881.985513,0.000000
25%,1.382534e+07,6.000000,-73.992065,40.734796,-73.991407,40.733823,1.000000
50%,2.774524e+07,8.500000,-73.981823,40.752592,-73.980093,40.753042,1.000000
75%,4.155535e+07,12.500000,-73.967154,40.767158,-73.963659,40.768001,2.000000
max,5.542357e+07,499.000000,57.418457,1644.421482,1153.572603,872.697628,208.000000

In [68]:
# Remove the amount that is less then 0
df = df[df['fare_amount'] > 0]

In [69]:
df.shape

(199977, 9)

In [70]:
# Passenger should be in range of 1 to 6
df = df[(df['passenger_count'] > 0) & (df['passenger_count'] <= 6)]

In [71]:
df.shape

(199268, 9)

In [72]:
df.describe()

,sr,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,1.992680e+05,199268.000000,199268.000000,199268.000000,199268.000000,199268.000000,199268.000000
mean,2.771561e+07,11.369418,-72.530113,39.937182,-72.528142,39.925350,1.689438
std,1.601418e+07,9.905877,11.434234,7.723680,13.119047,6.794163,1.305387
min,1.000000e+00,0.010000,-1340.648410,-74.015515,-3356.666300,-881.985513,1.000000
25%,1.382627e+07,6.000000,-73.992065,40.734796,-73.991410,40.733828,1.000000
50%,2.775597e+07,8.500000,-73.981825,40.752584,-73.980095,40.753041,1.000000
75%,4.155982e+07,12.500000,-73.967162,40.767157,-73.963664,40.767995,2.000000
max,5.542357e+07,499.000000,57.418457,1644.421482,1153.572603,872.697628,6.000000

In [73]:
# New York city coordinates roughly lies between : Latitude-(40 , 42) , Longitude-(-74 , -72)

df = df[
    (df['pickup_latitude'].between(40, 42)) & 
    (df['pickup_longitude'].between(-74, -72)) &
    (df['dropoff_latitude'].between(40, 42)) & 
    (df['dropoff_longitude'].between(-74, -72))
]

In [74]:
df.shape

(150026, 9)

In [75]:
df.describe()

,sr,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,1.500260e+05,150026.000000,150026.000000,150026.000000,150026.000000,150026.000000,150026.000000
mean,2.775886e+07,11.049904,-73.969079,40.755563,-73.967526,40.756468,1.684128
std,1.601773e+07,9.618461,0.040169,0.030281,0.038829,0.033173,1.304289
min,4.500000e+01,0.010000,-74.000000,40.128233,-74.000000,40.128418,1.000000
25%,1.388023e+07,5.700000,-73.987520,40.743716,-73.986090,40.743748,1.000000
50%,2.782930e+07,8.100000,-73.978340,40.758202,-73.976641,40.758472,1.000000
75%,4.162472e+07,12.000000,-73.964068,40.771147,-73.960698,40.772457,2.000000
max,5.542357e+07,499.000000,-72.750302,41.366138,-72.759090,41.366138,6.000000

In [76]:
# Distance between pickup and dropoff

def haversine_np(lon1, lat1, lon2, lat2):
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    km = 6367 * c
    return km

df['distance_km'] = haversine_np(df['pickup_longitude'], df['pickup_latitude'], 
                                 df['dropoff_longitude'], df['dropoff_latitude'])

In [77]:
df.head()

,sr,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,distance_km
0,24238194,52:06.0,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1,1.682266
1,27835199,04:56.0,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1,2.456047
3,25894730,22:21.0,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3,1.660640
4,17610152,47:00.0,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5,4.472640
5,44470845,27:09.0,4.9,2011-02-12 02:27:09 UTC,-73.969019,40.755910,-73.969019,40.755910,1,0.000000

In [78]:
df.shape

(150026, 10)

In [79]:
# Convert string in date time
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

df['hour'] = df['pickup_datetime'].dt.hour
df['day_of_week'] = df['pickup_datetime'].dt.dayofweek  # 0=Monday, 6=Sunday
df['month'] = df['pickup_datetime'].dt.month
df['year'] = df['pickup_datetime'].dt.year

In [80]:
df.head()

,sr,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,distance_km,hour,day_of_week,month,year
0,24238194,52:06.0,7.5,2015-05-07 19:52:06+00:00,-73.999817,40.738354,-73.999512,40.723217,1,1.682266,19,3,5,2015
1,27835199,04:56.0,7.7,2009-07-17 20:04:56+00:00,-73.994355,40.728225,-73.994710,40.750325,1,2.456047,20,4,7,2009
3,25894730,22:21.0,5.3,2009-06-26 08:22:21+00:00,-73.976124,40.790844,-73.965316,40.803349,3,1.660640,8,4,6,2009
4,17610152,47:00.0,16.0,2014-08-28 17:47:00+00:00,-73.925023,40.744085,-73.973082,40.761247,5,4.472640,17,3,8,2014
5,44470845,27:09.0,4.9,2011-02-12 02:27:09+00:00,-73.969019,40.755910,-73.969019,40.755910,1,0.000000,2,5,2,2011

In [81]:
# make weekend column to find rush

df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

In [82]:
# make the for every day : morning , afternoon , evening , night

bins = [0, 5, 12, 17, 21, 24]
labels = ["Night", "Morning", "Afternoon", "Evening", "Night"]

df['time_slots'] = pd.cut(df['hour'], bins=bins, labels=labels ,  right=False, ordered=False)

In [83]:
df.shape

(150026, 16)

In [84]:
df.head()

,sr,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,distance_km,hour,day_of_week,month,year,is_weekend,time_slots
0,24238194,52:06.0,7.5,2015-05-07 19:52:06+00:00,-73.999817,40.738354,-73.999512,40.723217,1,1.682266,19,3,5,2015,0,Evening
1,27835199,04:56.0,7.7,2009-07-17 20:04:56+00:00,-73.994355,40.728225,-73.994710,40.750325,1,2.456047,20,4,7,2009,0,Evening
3,25894730,22:21.0,5.3,2009-06-26 08:22:21+00:00,-73.976124,40.790844,-73.965316,40.803349,3,1.660640,8,4,6,2009,0,Morning
4,17610152,47:00.0,16.0,2014-08-28 17:47:00+00:00,-73.925023,40.744085,-73.973082,40.761247,5,4.472640,17,3,8,2014,0,Evening
5,44470845,27:09.0,4.9,2011-02-12 02:27:09+00:00,-73.969019,40.755910,-73.969019,40.755910,1,0.000000,2,5,2,2011,1,Night

In [85]:
df.drop(['sr' , 'key' , 'pickup_datetime'] , axis=1 ,inplace=True)

In [86]:
df.head()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,distance_km,hour,day_of_week,month,year,is_weekend,time_slots
0,7.5,-73.999817,40.738354,-73.999512,40.723217,1,1.682266,19,3,5,2015,0,Evening
1,7.7,-73.994355,40.728225,-73.994710,40.750325,1,2.456047,20,4,7,2009,0,Evening
3,5.3,-73.976124,40.790844,-73.965316,40.803349,3,1.660640,8,4,6,2009,0,Morning
4,16.0,-73.925023,40.744085,-73.973082,40.761247,5,4.472640,17,3,8,2014,0,Evening
5,4.9,-73.969019,40.755910,-73.969019,40.755910,1,0.000000,2,5,2,2011,1,Night

In [87]:
df.shape

(150026, 13)

In [88]:
# Remove the year column because it has only one value and this cannot improve model power

df.drop('year' , axis=1 , inplace=True)

In [89]:
df.head()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,distance_km,hour,day_of_week,month,is_weekend,time_slots
0,7.5,-73.999817,40.738354,-73.999512,40.723217,1,1.682266,19,3,5,0,Evening
1,7.7,-73.994355,40.728225,-73.994710,40.750325,1,2.456047,20,4,7,0,Evening
3,5.3,-73.976124,40.790844,-73.965316,40.803349,3,1.660640,8,4,6,0,Morning
4,16.0,-73.925023,40.744085,-73.973082,40.761247,5,4.472640,17,3,8,0,Evening
5,4.9,-73.969019,40.755910,-73.969019,40.755910,1,0.000000,2,5,2,1,Night

In [90]:
df.shape

(150026, 12)

# Model Preprocessing

In [91]:
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.model_selection import train_test_split
import pickle

In [92]:
df['hour'].unique()

array([19, 20,  8, 17,  2,  7, 14, 11, 22,  9,  0, 23, 16,  6,  5, 21, 15,
       10, 18, 13,  3,  1,  4, 12], dtype=int32)

In [93]:
#1. Make ALL posible categoies list for 5 columns
hours_list = list(range(24))                                            # 0 se 23
days_list = list(range(7))                                              # 0 se 6
months_list = list(range(1, 13))                                        # 1 se 12
passengers_list = [1 , 2 , 3 , 4 , 5 , 6]                               # 1 se 6
time_slots_list = ["Night", "Morning", "Afternoon", "Evening"] 

#2. Make list of list for all this lists
all_categories = [hours_list, days_list, months_list, passengers_list, time_slots_list]

# 3. OneHotEncoder initialize 
encoder = OneHotEncoder(categories=all_categories, sparse_output=False, handle_unknown='error')

# 4. Make the list of my columns name
categorical_cols = ['hour', 'day_of_week', 'month', 'passenger_count', 'time_slots']

# 5. Apply fit_transform
encoded_array = encoder.fit_transform(df[categorical_cols])

# 6. Make dataframe for this new columns
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(categorical_cols))

# 7 . Drop the original 5 columns and concat this new dataframe with our original old dataframe
df_remaining = df.drop(categorical_cols, axis=1).reset_index(drop=True)
df_final = pd.concat([df_remaining, encoded_df], axis=1)

In [94]:
df_final.head()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,distance_km,is_weekend,hour_0,hour_1,hour_2,...,passenger_count_1,passenger_count_2,passenger_count_3,passenger_count_4,passenger_count_5,passenger_count_6,time_slots_Night,time_slots_Morning,time_slots_Afternoon,time_slots_Evening
0,7.5,-73.999817,40.738354,-73.999512,40.723217,1.682266,0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,7.7,-73.994355,40.728225,-73.994710,40.750325,2.456047,0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,5.3,-73.976124,40.790844,-73.965316,40.803349,1.660640,0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,16.0,-73.925023,40.744085,-73.973082,40.761247,4.472640,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,4.9,-73.969019,40.755910,-73.969019,40.755910,0.000000,1,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [95]:
df_final.shape

(150026, 60)

In [96]:
y = df_final.pop('fare_amount')

In [97]:
X = df_final

In [98]:
# save the feature order
with open("feature_order.pkl", "wb") as file:
    pickle.dump(X.columns.tolist(), file)

In [99]:
X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size=0.25 , random_state=42
)

In [100]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [101]:
X_train.shape

(112519, 59)

In [102]:
# Learning
# -> In latitude and Longitude range fix section , swap this words so got only 79 rows
# -> In Hour and moth column i saw that big number will capture as big weight but this not posible for time data
# -> I saw that year column has only 1 value in all row so it does not give the power to learn model better so drop it
# -> In hour column i saw only 20 unique value so before encoding make the list of 0 to 24

In [103]:
# save scaler and encoder for later use
with open('encoder.pkl' , 'wb') as file:
    pickle.dump(encoder , file)

with open('scaler.pkl' , 'wb') as file:
    pickle.dump(scaler , file)

# ANN regression Model trianing

In [42]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [49]:
model = Sequential([
    Dense(64 , activation='relu' , input_shape=(X_train.shape[1],)),
    Dense(32 , activation='relu'),
    Dense(1)            #Output layer for regression don't need activation function
])

d:\ML projects\Uber Fare Prediction\venvforuber\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [44]:
# def create_model(neurons=32 , layers=1):
#     model = Sequential()
#     model.add(Dense(neurons , activation='relu' , input_shape=(X_train.shape[1],)))

#     for _ in range(layers-1):
#         model.add(Dense(neurons , activation='relu'))

#     model.add(Dense(1))         #Output layer for regression don't need activation function

#     # Compile the model
#     model.compile(optimizer='adam' , loss='mean_absolute_error' , metrics=['mae'])

#     return model

In [50]:
model.compile(optimizer='adam' , loss='mean_absolute_error' , metrics=['mae'])

In [51]:
# Create Keras Regressor Model
from scikeras.wrappers import KerasRegressor

model = KerasRegressor(model=model , verbose=1)

In [46]:
# # Define the Grid search paramenter
# param_grid = {
#     'neurons' : [16 , 32 , 64 , 128],
#     'layers' : [1,2],
#     'epochs' : [50 ,100]
# }

# # Perfornm Grid Search
# from sklearn.model_selection import GridSearchCV

# grid = GridSearchCV(estimator=model , param_grid=param_grid , n_jobs=-1 ,verbose=1, cv=3)
# grid_result = grid.fit(X_train , y_train)

In [47]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_loss',      # Focus on validation loss
    patience=15,              # for 5 epochs if loss doesn't change too much model will stop training
    restore_best_weights=True # After Stop the training it restore the best weights
)

In [53]:
# Train the model 
history = model.fit(
    X_train , y_train,
    validation_data = (X_test , y_test),
    epochs = 50,
    callbacks = [early_stopping]
)

Epoch 1/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.9917 - mae: 1.9917 - val_loss: 1.9862 - val_mae: 1.9862
Epoch 2/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.9839 - mae: 1.9839 - val_loss: 1.9559 - val_mae: 1.9559
Epoch 3/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.9706 - mae: 1.9706 - val_loss: 1.9487 - val_mae: 1.9487
Epoch 4/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.9627 - mae: 1.9627 - val_loss: 1.9790 - val_mae: 1.9790
Epoch 5/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 1.9490 - mae: 1.9490 - val_loss: 1.9430 - val_mae: 1.9430
Epoch 6/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.9439 - mae: 1.9439 - val_loss: 1.9491 - val_mae: 1.9491
Epoch 7/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.9358 - mae: 1.9358 - val_loss: 1.9739 - val_mae: 1.9739
Epoch 8/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.9259 - mae: 1.9259 - val_loss: 1.9284 - val_mae: 1.9284
Epoch 9/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.9214 - mae: 1.9214 - val_loss: 1.9245 - val_mae: 1.9245
Epoch 10/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.9132 - mae: 1.9132 - val_loss: 1.9200 - val_mae: 1.9200
Epoch 11/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 1.9071 - mae: 1.9071 - val_loss: 1.9301 - val_mae: 1.9301
Epoch 12/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.9052 - mae: 1.9052 - val_loss: 1.9301 - val_mae: 1.9301
Epoch 13/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8998 - mae: 1.8998 - val_loss: 1.9592 - val_mae: 1.9592
Epoch 14/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8957 - mae: 1.8957 - val_loss: 1.9162 - val_mae: 1.9162
Epoch 15/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 1.8924 - mae: 1.8924 - val_loss: 1.9153 - val_mae: 1.9153
Epoch 16/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8898 - mae: 1.8898 - val_loss: 1.9221 - val_mae: 1.9221
Epoch 17/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8856 - mae: 1.8856 - val_loss: 1.9169 - val_mae: 1.9169
Epoch 18/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8818 - mae: 1.8818 - val_loss: 1.9039 - val_mae: 1.9039
Epoch 19/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8792 - mae: 1.8792 - val_loss: 1.9004 - val_mae: 1.9004
Epoch 20/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8749 - mae: 1.8749 - val_loss: 1.9141 - val_mae: 1.9141
Epoch 21/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8749 - mae: 1.8749 - val_loss: 1.9130 - val_mae: 1.9130
Epoch 22/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8698 - mae: 1.8698 - val_loss: 1.9034 - val_mae: 1.9034
Epoch 23/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8684 - mae: 1.8684 - val_loss: 1.9099 - val_mae: 1.9099
Epoch 24/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8638 - mae: 1.8638 - val_loss: 1.9139 - val_mae: 1.9139
Epoch 25/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8611 - mae: 1.8611 - val_loss: 1.9139 - val_mae: 1.9139
Epoch 26/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8608 - mae: 1.8608 - val_loss: 1.9006 - val_mae: 1.9006
Epoch 27/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8573 - mae: 1.8573 - val_loss: 1.9289 - val_mae: 1.9289
Epoch 28/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8566 - mae: 1.8566 - val_loss: 1.9051 - val_mae: 1.9051
Epoch 29/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8539 - mae: 1.8539 - val_loss: 1.9209 - val_mae: 1.9209
Epoch 30/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8519 - mae: 1.8519 - val_loss: 1.8991 - val_mae: 1.8991
Epoch 31/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8485 - mae: 1.8485 - val_loss: 1.9003 - val_mae: 1.9003
Epoch 32/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 1.8467 - mae: 1.8467 - val_loss: 1.8964 - val_mae: 1.8964
Epoch 33/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 120s 34ms/step - loss: 1.8460 - mae: 1.8460 - val_loss: 1.8930 - val_mae: 1.8930
Epoch 34/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8443 - mae: 1.8443 - val_loss: 1.9197 - val_mae: 1.9197
Epoch 35/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8441 - mae: 1.8441 - val_loss: 1.9177 - val_mae: 1.9177
Epoch 36/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8404 - mae: 1.8404 - val_loss: 1.8969 - val_mae: 1.8969
Epoch 37/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8376 - mae: 1.8376 - val_loss: 1.9007 - val_mae: 1.9007
Epoch 38/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8357 - mae: 1.8357 - val_loss: 1.9222 - val_mae: 1.9222
Epoch 39/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 1.8343 - mae: 1.8343 - val_loss: 1.8930 - val_mae: 1.8930
Epoch 40/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8325 - mae: 1.8325 - val_loss: 1.8996 - val_mae: 1.8996
Epoch 41/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 1.8306 - mae: 1.8306 - val_loss: 1.8972 - val_mae: 1.8972
Epoch 42/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8304 - mae: 1.8304 - val_loss: 1.9051 - val_mae: 1.9051
Epoch 43/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8277 - mae: 1.8277 - val_loss: 1.9005 - val_mae: 1.9005
Epoch 44/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 1.8273 - mae: 1.8273 - val_loss: 1.8959 - val_mae: 1.8959
Epoch 45/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 1.8256 - mae: 1.8256 - val_loss: 1.9055 - val_mae: 1.9055
Epoch 46/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8233 - mae: 1.8233 - val_loss: 1.8952 - val_mae: 1.8952
Epoch 47/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8242 - mae: 1.8242 - val_loss: 1.9006 - val_mae: 1.9006
Epoch 48/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8225 - mae: 1.8225 - val_loss: 1.8947 - val_mae: 1.8947
Epoch 49/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 1.8194 - mae: 1.8194 - val_loss: 1.9116 - val_mae: 1.9116
Epoch 50/50
3517/3517 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.8212 - mae: 1.8212 - val_loss: 1.9036 - val_mae: 1.9036

In [57]:
test_score= model.score(X_test , y_test)
print(f"Test Score : {test_score}")

1173/1173 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step
Test Score : 0.7538251990674472

In [ ]:
test_loss, test_mae = model.model_.evaluate(X_test, y_test)
print(f"Test MAE : {test_mae}")

1173/1173 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 1.9036 - mae: 1.9036
Test MAE : 1.903558611869812

In [60]:
model.model_.save('Uber_fare_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_callback = EarlyStopping(monitor='val_loss' , patience=5 , restore_best_weights=True)